var name = prompt('Ismingizni kiriting')
console.log('Mening ismim '+ name)
var age = prompt('Yoshingizni kiriting')
console.log('Mening yoshim '+ age +' da')
var misol1 = +prompt("Misolni yeching " + '15/3=?')
console.log("Birinchi misol 15 / 3 = 5 Sizning javobingiz " + misol1)
var misol2 = +prompt("Misolni yeching " + '7-4=?')
console.log("Ikkinchi misol 7 - 4 = 3 Sizning javobingiz " + misol2)
var misol3 = +prompt("Misolni yeching " + '22%3=?')
console.log("Uchinchi misol 22 % 3 = 1 Sizning javobingiz " + misol3)
var misol4 = +prompt("Misolni yeching " + '12+3=?')
console.log("To'rtinchi misol 12 + 3 = 15 Sizning javobingiz " + misol4)
var misol5 = +prompt("Misolni yeching " + '10*5=?')
console.log("Beshinchi misol 10 * 5 = 50 Sizning javobingiz " + misol5)
var misol6 = +prompt("Misolni yeching " + '34-10=?')
console.log("To'rtinchi misol 34 - 10 = 24 Sizning javobingiz " + misol6)
var misol7 = +prompt("Misolni yeching " + '14%4=?')
console.log("To'rtinchi misol 14 % 4 = 2 Sizning javobingiz " + misol7)
var alert = alert("Misol javoblarini korish")